# ?????????????? ?????????? ????????? WEdit6
# ??????????, ? ??????? ????? ?????????? ?????? ?? ??????? deploy.linux.locale
programmPath=/home/svj/Programm/my/wedit6
# ???? ?? ?????????? rt.jar, ? ??????? ????????? swing
java8.rt.jar=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
